---
abstract: 'PID file operations'
author:
  - 'Oleg A. Mamontov, C<< <oleg at mamontov.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.98'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pid-File-Flock
no_index:
  directory:
    - inc
    - t
requires:
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
