--- #YAML:1.0
name:               Pid-File-Flock
version:            0.01
abstract:           PID file operations
author:
    - Oleg A. Mamontov <oleg@mamontov.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
